version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/be
    overwrite: yes
permissions:
  - object: /home/ubuntu/be/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu